# Generated by Django 3.2.8 on 2022-02-15 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('stid', models.IntegerField(primary_key=True, serialize=False)),
                ('stname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MarksModel',
            fields=[
                ('marksid', models.IntegerField(primary_key=True, serialize=False)),
                ('math', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('computer', models.IntegerField()),
                ('stid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='patient.studentmodel')),
            ],
        ),
    ]
