# Generated by Django 3.2.8 on 2021-10-30 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0003_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AvailableTime', models.DateField()),
                ('AvailableDate', models.DateField()),
                ('ConsultationFee', models.IntegerField()),
                ('FollowUpFee', models.IntegerField()),
                ('WithinDuration', models.DateField()),
                ('PerPatientConsultancyDuration', models.CharField(blank=True, max_length=50, null=True)),
                ('NIDPhoto', models.ImageField(upload_to='Doctor/NidImage')),
                ('ProfilePhoto', models.ImageField(upload_to='Doctor/ProfileImage')),
                ('About', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
