# Generated by Django 3.2.8 on 2021-12-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_experience_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='From',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='To',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
