# Generated by Django 3.2.8 on 2022-01-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_auto_20211212_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='AvailableDate',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='AvailableDay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='AvailableTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
