# Generated by Django 3.2.8 on 2022-01-19 07:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0008_auto_20220118_0618'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctorProfile',
            new_name='DoctorInfo',
        ),
    ]
