# Generated by Django 3.2.8 on 2022-01-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_alter_doctorinfo_withinduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='Specialist',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
