# Generated by Django 3.2.8 on 2022-02-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0014_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
