# Generated by Django 3.2.13 on 2022-05-22 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_useraccount_isapproved'),
        ('doctor', '0015_alter_category_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qualificationInfo', to='accounts.doctor'),
        ),
    ]
