# Generated by Django 3.2.13 on 2022-05-23 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0016_qualification_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experienceInfo', to=settings.AUTH_USER_MODEL),
        ),
    ]
