# Generated by Django 3.2.13 on 2022-05-23 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0018_auto_20220523_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='Name',
        ),
    ]
