# Generated by Django 3.2.13 on 2022-05-23 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_review_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='NumberOfReview',
        ),
    ]
