# Generated by Django 3.2.8 on 2021-10-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='NidOrPassport',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='RegistrationNumberBMDC',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
