# Generated by Django 3.2.8 on 2021-11-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_patient_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='IsApproved',
            field=models.BooleanField(default=False),
        ),
    ]
